server:
  port: ${SERVER_PORT:8088}  # Puerto del Login Service

spring:
  application:
    name: login-service   # Nombre con el que se registra en Eureka
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/usermgmt_db
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true   # Opcional, para ver queries en consola

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
