server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: false

      routes:
        # Rutas para Order Management Service
        - id: order-service
          uri: http://order-service:3000
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/order/(?<path>.*), /order/${path}

        # Rutas para User Management Service  
        - id: user-service
          uri: http://user-service:8000
          predicates:
            - Path=/api/customer/**
          filters:
            - RewritePath=/api/customer/(?<path>.*), /customer/${path}

        # Ruta para health checks
        - id: order-service-health
          uri: http://order-service:3000
          predicates:
            - Path=/api/order-health
          filters:
            - RewritePath=/api/order-health, /health

        - id: user-service-health
          uri: http://user-service:8000
          predicates:
            - Path=/api/user-health
          filters:
            - RewritePath=/api/user-health, /health

        # Ruta para Login Service
        - id: login-service
          uri: http://login-service:8088
          predicates:
            - Path=/api/login/**
          filters:
            - StripPrefix=2

      # 🌐 CONFIGURACIÓN GLOBAL DE CORS
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods: "GET,POST,PUT,DELETE,OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true

      # Evita encabezados duplicados de CORS en respuestas
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: false
    register-with-eureka: false
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
